const translations = [
  "my personal language archive",
  "arsip bahasa pribadi lon",
  "my persoonlike taalargief",
  "arkivi im personal i gjuhës",
  "የእኔ የግል ቋንቋ ማህደር",
  "أرشيفي الشخصي للغة",
  "իմ անձնական լեզվաբառարան",
  "মোৰ ব্যক্তিগত ভাষা আৰ্হাইভ",
  "el mio archivu personal de llingua",
  "mənim şəxsi dil arxivim",
  "arsip basa pribadiangku",
  "আমার ব্যক্তিগত ভাষা আর্কাইভ",
  "минең шәхси тел архивым",
  "nire hizkuntza pertsonaleko artxiboa",
  "arsip bahasa pribadi au",
  "мой асабісты архіў моў",
  "हमार व्यक्तिगत भाषा अभिलेख",
  "sariling arkibo nin lenggwahe",
  "आंनि गावारि रावनि आर्काइभ",
  "moj lični jezični arhiv",
  "моят личен архив на езици",
  "我個人語言檔案",
  "el meu arxiu personal de llengües",
  "akong personal nga archive sa pinulongan",
  "मोर निजी भाषा संग्रह",
  "我的个人语言档案",
  "我的個人語言檔案",
  "u mio archiviu linguisticu persunale",
  "moj osobni jezični arhiv",
  "můj osobní jazykový archiv",
  "mit personlige sprogarkiv",
  "آرشیف شخصی زبان من",
  "އަޅުގަނޑުގެ ޕާސަނަލް ލެންގުއޭޖް އާކައިވް",
  "मेरा निजी भाशा संग्रह",
  "mijn persoonlijke taalarchief",
  "minu isiklik keelearhiiv",
  "mín persónliga málarkiv",
  "noqu ivola ni vosa vakatamata",
  "aking personal na talaan ng wika",
  "henkilökohtainen kieliarkistoni",
  "mon archive personnelle de langues",
  "mijn persoanlike taalargyf",
  "mi archivio linguistic personâl",
  "o meu arquivo persoal de idiomas",
  "Lulimi Lwange Archive",
  "ჩემი პირადი ენობრივი არქივი",
  "mein persönliches Spracharchiv",
  "το προσωπικό μου αρχείο γλωσσών",
  "મારા અંગત ભાષા આર્કાઇવ",
  "achiv lang pèsonèl mwen",
  "ma'ajiyar harshena ta kaina",
  "ארכיון השפה האישי שלי",
  "akong personal nga archive sang lenguahe",
  "मेरा व्यक्तिगत भाषा संग्रह",
  "Kuv Tus Kheej Cov Lus Archive",
  "az én személyes nyelvi archívumom",
  "arkib bahasa enda sida",
  "persónuleg tungumálaskrá",
  "ọrụ nkwado asụsụ nkeonwe m",
  "ti personal a pagipalaak ti pagsasao",
  "arsip bahasa pribadi saya",
  "Nanminigiyamnik Uqauhirnik Tutquqtiqhimayut",
  "ᓇᖕᒥᓂᖅ ᐅᖃᐅᓯᕐᓄᑦ ᑐᖅᑯᖅᑕᐅᓯᒪᔪᑦ",
  "nangminiq uqausirnut tuqquqtausimajut",
  "mo chartlann teanga pearsanta",
  "il mio archivio linguistico personale",
  "mi personal langwij aakaav",
  "私の個人的な言語アーカイブ",
  "arsip basa pribadiku",
  "mi arkivu di lingi personalmente",
  "ನನ್ನ ವೈಯಕ್ತಿಕ ಭಾಷಾ ಸಂಗ್ರಹ",
  "aking personal a arkibu ning amanu",
  "میٲنۍ ذٲتی لینگویج آرکائیو",
  "менің жеке тіл архивім",
  "សារមន្ទីរភាសាបុគ្គលរបស់ខ្ញុំ",
  "ububiko bwanjye bw'ururimi bwite",
  "म्हजो वैयक्तीक भाशेचो संग्रह",
  "나의 개인 언어 기록",
  "mi pɛsonl lanɡwij ɑkaiv",
  "ئەرشیفی زمانی تایبەتی من",
  "Arşîva zimanê min a şexsî",
  "менин жеке тил архивим",
  "ບັນທຶກພາສາສ່ວນຕົວຂອງຂ້ອຍ",
  "mea personalis lingua archivum",
  "mans personīgais valodu arhīvs",
  "o mè archivio persunâ de lenga",
  "mien persoonlike taolarchief",
  "arkivu na ngai ya lokota",
  "mano asmeninis kalbų archyvas",
  "ol mè archivi linguistic personal",
  "Mój wósobinski rěcny archiw",
  "mäi perséinleche Sprooch-Archiv",
  "мој личен јазичен архив",
  "हमर व्यक्तिगत भाषा अभिलेख",
  "ny tahiry manokana amin'ny fiteniko",
  "arkib bahasa peribadi saya",
  "എന്റെ വ്യക്തിഗത ഭാഷാ ആർക്കൈവ്",
  "l-arkivju personali tiegħi tal-lingwa",
  "माझा वैयक्तिक भाषा आर्काइव्ह",
  "म्हारो व्यक्तिगत भाषा संग्रह",
  "mo prosenn arkiv lang",
  "arsip baso pribadiku",
  "миний хувийн хэлний архив",
  "ᠮᠢᠨᠦ ᠬᠣᠪᠢ ᠶᠢᠨ ᠬᠡᠯᠡᠨ ᠦ ᠳᠠᠩᠰᠠ",
  "ကျွန်ုပ်၏ကိုယ်ပိုင်ဘာသာစကားသိုလှောင်ခြင်း",
  "tuhinga reo whaiaro",
  "मेरो व्यक्तिगत भाषा अभिलेख",
  "mitt personlige språkararkiv",
  "mitt personlege språkarkiv",
  "zokumbukira zanga za chinenero",
  "mon archiu lingüistic personal",
  "ମୋର ବ୍ୟକ୍ତିଗତ ଭାଷା ଆର୍କାଇଭ୍",
  "mi arshivo personal di idioma",
  "زما شخصي ژبني آرشيف",
  "آرشیو شخصی زبان من",
  "moja osobista archiwum językowe",
  "meu arquivo pessoal de idiomas",
  "o meu arquivo pessoal de línguas",
  "ਮੇਰਾ ਨਿੱਜੀ ਭਾਸ਼ਾ ਆਰਕਾਈਵ",
  "میری ذاتی زبانی آرکائیو",
  "Ma archivo jä'i ar hñä",
  "arhiva mea personală de limbi",
  "archive yanje y'indimi bwite",
  "мой личный языковой архив",
  "laʻu faʻasoa gagana patino",
  "मम व्यक्तिगतभाषासङ्ग्रहः",
  "su mèu archìviu linguìsticu personale",
  "мој лични језички архив",
  "polokelo ea ka ea puo",
  "mon prop arkiv lang",
  "nguva yangu yekuchengetera mitauro",
  "lu me arquivu di lingua privatu",
  "منهنجو ذاتي ٻولي آرڪائيو",
  "මගේ පුද්ගලික භාෂා නඩුව",
  "môj osobný jazykový archív",
  "moj osebni jezikovni arhiv",
  "keydka luqaddayda shaqsiga ah",
  "mi archivo personal de idiomas",
  "arsip basa pribadi abdi",
  "maktaba yangu binafsi ya lugha",
  "mitt personliga språkararkiv",
  "Архиви шахсии забонии ман",
  "எனது தனிப்பட்ட மொழி காப்பகம்",
  "минем шәхси тел архивым",
  "నాకు చెందిన వ్యక్తిగత భాషా ఆర్కైవ్",
  "arkivu lian personali hau",
  "คลังภาษาส่วนตัวของฉัน",
  "ངའི་མི་སྒེར་གྱི་སྐད་ཡིག་ཡིག་ཚགས་",
  "ውልቃዊ መዛግብተይ",
  "ʻAkaivi ʻo ʻeku lea fakafonua fakatautaha",
  "benim kişisel dil arşivim",
  "meniň şahsy dil arkiviň",
  "мій особистий мовний архів",
  "Mój wosobinski rěčny archiw",
  "میرا ذاتی زبان کا محفوظہ",
  "مەنىڭ شەخسىي تىل ئەسلىھەرىم",
  "mening shaxsiy til arxivim",
  "el me archivio personale de linguaggi",
  "kho lưu trữ ngôn ngữ cá nhân của tôi",
  "akong personal nga archive han pinulongan",
  "fy archif iaith personol",
  "i-archivu yam yolwimi lwam",
  "מייַן פערזענלעכער שפראך ארכיוו",
  "Ibi-ipamọ ede ti ara mi",
  "In archivo máaxo'ob t'aano'",
  "igugu lami lolimi lomuntu siqu"
];

let lastMinute = "";

function updateFooter() {
  const now = new Date();
  const currentMinute = `${now.getFullYear()}-${now.getMonth()}-${now.getDate()}-${now.getHours()}-${now.getMinutes()}`;

  if (currentMinute !== lastMinute) {
    lastMinute = currentMinute;
    
    let hash = 0;
    for (let i = 0; i < currentMinute.length; i++) {
      hash = currentMinute.charCodeAt(i) + ((hash << 5) - hash);
    }
    
    const index = Math.abs(hash) % translations.length;
    document.getElementById("daily-footer").textContent = translations[index];
  }
}

updateFooter();

setInterval(updateFooter, 10000);